name: avilatek_bloc
description: Avila Tek Blocs/Cubits
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  bloc_test: ^9.1.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.5
  very_good_analysis: ^5.0.0
